name: vhydro-env
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.9
  - streamlit>=1.10.0
  - pandas>=1.3.0
  - numpy>=1.20.0
  - matplotlib>=3.4.0
  - seaborn>=0.11.0
  - scikit-learn>=0.24.0
  - plotly>=5.3.0
  - networkx>=2.6.0
  - tensorflow=2.11.0
  - lasio>=0.29.0
  - pip>=21.0.0
  - pip:
    - git+https://github.com/VenkateshwaranB/stellargraph.git
    - pillow>=8.0.0